from typing import List, Dict, Any, TypedDict

# LangGraph is used to manage the state and transitions between different AI agents
from langgraph.graph import StateGraph, END

from agents.llm_client import OpenAIClient
from agents.workers import research_agent, analysis_agent, opinion_agent, editor_agent
from utils.logger import setup_logger

logger = setup_logger(__name__)

# NewsletterState defines the data structure that is passed between agents
# Each agent reads from this state and updates specific fields.
class NewsletterState(TypedDict):
    raw_articles: List[Dict]      # Initial list of articles fetched by the crawler
    research_summary: str         # Summary generated by the Researcher Agent
    key_insights: str             # Insights generated by the Analyst Agent
    opinion_analysis: str         # Editorial commentary generated by the Opinion Writer
    final_newsletter: str         # The final formatted newsletter produced by the Editor


class NewsletterAgents:
    """
    Orchestrates the multi-agent workflow using LangGraph.
    It defines how data flows from one specialized agent to the next.
    """
    def __init__(self):
        # OpenAIClient handles communication with the LLM (GPT-4o)
        self.llm_client = OpenAIClient()
        # Compile the graph upon initialization
        self.graph = self._create_agent_graph()

    def _create_agent_graph(self) -> StateGraph:
        """
        Defines the execution flow (the 'Graph') for the agents.
        """
        # Initialize the graph with our state definition
        workflow = StateGraph(NewsletterState)

        # Add Nodes: These are the actual processing steps
        # Each node calls a specific worker function with the current state and LLM client
        workflow.add_node("researcher", lambda s: research_agent(s, self.llm_client))
        workflow.add_node("analyst", lambda s: analysis_agent(s, self.llm_client))
        workflow.add_node("opinion_writer", lambda s: opinion_agent(s, self.llm_client))
        workflow.add_node("editor", lambda s: editor_agent(s, self.llm_client))

        # Add Edges: These define the sequential order of operations
        workflow.add_edge("researcher", "analyst")
        workflow.add_edge("analyst", "opinion_writer")
        workflow.add_edge("opinion_writer", "editor")
        workflow.add_edge("editor", END) # The workflow ends after the Editor finishes

        # Set the entry point for the graph
        workflow.set_entry_point("researcher")

        # Compile the graph into an executable 'runnable'
        return workflow.compile()

    def process_articles(self, articles: List[Dict]) -> Dict[str, Any]:
        """
        Executes the entire agent pipeline for a given set of articles.
        
        Args:
            articles: A list of dictionaries, each representing an article.
            
        Returns:
            The final state of the graph, including the generated newsletter.
        """
        logger.info(f"Processing {len(articles)} articles through agent workflow")

        # Initialize the state with the raw articles
        initial_state: NewsletterState = {
            "raw_articles": articles,
            "research_summary": "",
            "key_insights": "",
            "opinion_analysis": "",
            "final_newsletter": "",
        }

        try:
            # Invoke the graph to start the sequential processing
            final_state = self.graph.invoke(initial_state)
            logger.info("Agent workflow completed successfully")
            return final_state
        except Exception as e:
            # Capture and log errors within the pipeline
            logger.error(f"Error in agent workflow: {str(e)}")
            return initial_state

